[project]
name = "bus-box"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gtfs-realtime-bindings>=1.0.0",
    "partridge[full]>=1.1.2",
    "rich>=13.9.4",
    "ruff>=0.9.2",
]
